services:
  - type: web
    name: openapi-viewer
    env: docker
    plan: free
    autoDeploy: false
    dockerfilePath: ./render/Dockerfile
    dockerContext: ./render
    envVars:
      - key: CONFIG_URL
        value: https://raw.githubusercontent.com/devatherock/api-specs/master/render/swagger-config.yml