work_directory: &work_directory
  working_directory: ~/api-specs

resource_class: &resource_class
  resource_class: small
  
executors:
  docker-executor:
    docker:
      - image: cimg/go:1.14
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    <<: *resource_class
    <<: *work_directory  

version: 2.1
jobs:
  deploy:
    executor: docker-executor
    steps:
      - run:
          name: Trigger deployment to render.com
          command: |
            curl $RENDER_DEPLOY_HOOK
            
  notify:
    docker:
      - image: devatherock/simple-slack:0.7.0
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    <<: *resource_class
    environment:
      TEXT: "Success: {{.CircleBuildUrl}} by {{.CircleUsername}}"
      CHANNEL: general
      TITLE: "Build completed"
    steps:
      - run: /bin/simpleslack -c "#33ad7f"

workflows:
  version: 2.1
  build_deploy:
    jobs:
      - deploy:
          context:
            - docker-credentials
          filters:
            branches:
              only: master
      - notify:
          context:
            - docker-credentials
            - slack-webhook
          requires:
            - deploy