openapi: 3.0.1
info:
  title: artifactory-badge
  version: v1
servers:
- url: http://localhost:8080
  description: The server where the application is hosted. Defaulted to localhost
paths:
  /docker/image-size:
    get:
      summary: getImageSize
      description: Generates the image size badge
      operationId: getImageSize
      parameters:
      - name: package
        in: query
        description: The full path to the docker image within the artifactory docker
          registry
        required: true
        schema:
          type: string
        example: docker/devatherock/drone-yaml-validator
      - name: tag
        in: query
        description: The docker image tag for which to generate the badge
        required: true
        schema:
          type: string
          default: latest
      - name: label
        in: query
        description: The label to use in the generated badge
        required: true
        schema:
          type: string
          default: image size
      responses:
        "200":
          description: An XML representing the SVG image size badge
          content:
            image/svg+xml; charset=utf-8:
              schema:
                type: string
  /docker/image_size:
    get:
      summary: getImageSize
      description: Generates the image size badge
      operationId: getImageSize_1
      parameters:
      - name: package
        in: query
        description: The full path to the docker image within the artifactory docker
          registry
        required: true
        schema:
          type: string
        example: docker/devatherock/drone-yaml-validator
      - name: tag
        in: query
        description: The docker image tag for which to generate the badge
        required: true
        schema:
          type: string
          default: latest
      - name: label
        in: query
        description: The label to use in the generated badge
        required: true
        schema:
          type: string
          default: image size
      responses:
        "200":
          description: An XML representing the SVG image size badge
          content:
            image/svg+xml; charset=utf-8:
              schema:
                type: string
  /docker/layers:
    get:
      summary: getImageLayers
      description: Generates the layers badge
      operationId: getImageLayers
      parameters:
      - name: package
        in: query
        description: The full path to the docker image within the artifactory docker
          registry
        required: true
        schema:
          type: string
        example: docker/devatherock/drone-yaml-validator
      - name: tag
        in: query
        description: The docker image tag for which to generate the badge
        required: true
        schema:
          type: string
          default: latest
      - name: label
        in: query
        description: The label to use in the generated badge
        required: true
        schema:
          type: string
          default: layers
      responses:
        "200":
          description: An XML representing the SVG layers badge
          content:
            image/svg+xml; charset=utf-8:
              schema:
                type: string
  /docker/pulls:
    get:
      summary: getImagePullCount
      description: Generates the docker pulls badge
      operationId: getImagePullCount
      parameters:
      - name: package
        in: query
        description: The full path to the docker image within the artifactory docker
          registry
        required: true
        schema:
          type: string
        example: docker/devatherock/drone-yaml-validator
      - name: label
        in: query
        description: The label to use in the generated badge
        required: true
        schema:
          type: string
          default: docker pulls
      responses:
        "200":
          description: An XML representing the SVG docker pulls badge
          content:
            image/svg+xml; charset=utf-8:
              schema:
                type: string
  /version:
    get:
      summary: getLatestVersion
      description: Generates the version badge
      operationId: getLatestVersion
      parameters:
      - name: package
        in: query
        description: The full path to the docker image within the artifactory docker
          registry
        required: true
        schema:
          type: string
        example: docker/devatherock/drone-yaml-validator
      - name: label
        in: query
        description: The label to use in the generated badge
        required: true
        schema:
          type: string
          default: version
      - name: sort
        in: query
        description: The attribute based on which to determine the latest version
        required: true
        schema:
          type: string
          default: date
      responses:
        "200":
          description: An XML representing the SVG version badge
          content:
            image/svg+xml; charset=utf-8:
              schema:
                type: string
