openapi: 3.0.1
info:
  title: Velocity Template Tester
  description: Velocity Template Tester API
  contact:
    name: devatherock
    url: https://github.com/devatherock
  version: 1.2.0
servers:
- url: https://velocity-template-tester.onrender.com
  description: The server where the application is hosted
paths:
  /api/expandTemplate:
    post:
      summary: Handles a JSON request payload
      description: Handles a JSON request payload
      operationId: expandJsonTemplate
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              type: string
          application/x-yaml:
            schema:
              type: string
        required: true
      responses:
        "200":
          description: response
          content:
            text/plain:
              schema:
                type: string
                description: Handles a JSON request payload
            text/html:
              schema:
                type: string
                description: Handles a JSON request payload
