openapi: 3.0.1
info:
  title: Velocity Template Tester
  description: Velocity Template Tester API
  contact:
    name: devatherock
    url: https://github.com/devatherock
  version: 1.2.0
servers:
- url: https://velocity-template-tester.onrender.com
  description: The server where the application is hosted
paths:
  /api/expandTemplate:
    post:
      summary: expandJsonTemplate
      description: Accepts a JSON request and expands the supplied Velocity template
      operationId: expandJsonTemplate
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExpandTemplateRequest'
          application/x-yaml:
            schema:
              type: string
        required: true
      responses:
        "200":
          description: the expanded template string/html
          content:
            text/plain:
              schema:
                type: string
                example: Hello foo
            text/html:
              schema:
                type: string
                example: <html>Hello!</html>
components:
  schemas:
    ExpandTemplateRequest:
      required:
      - template
      type: object
      properties:
        template:
          type: string
          description: The Velocity template to expand
          example: "Hello ${user}"
        parameters:
          type: object
          additionalProperties: true
          description: Parameters to use to expand the template
          nullable: true
      description: Represents a request to expand a template
